# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor'
  pod 'CapacitorCordova'
end

target 'Plugin' do
  capacitor_pods
  pod 'FacebookCore', '0.9.0'
  pod 'FacebookLogin', '0.9.0'
end

target 'PluginTests' do
  capacitor_pods
end
